import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"
import ScrollToTopPage from "./components/ScrollToTopPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sabai Senpom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <div className="mb-10 md:mb-0">
          <Footer />
        </div>
        <ScrollToTopPage />
      </body>
    </html>
  );
}
